package com.example.cfsf.pojo;

public enum CodeType {
    JAVA, PYTHON, C, CPLUSPLUS, JAVASCRIPT, TYPESCRIPT, RUBY, SWIFT, KOTLIN, GO, RUST, SCALA, GROOVY, PERL, PHP, R, SHELL, SQL, HTML, CSS, XML, JSON, YAML, MARKDOWN, LATEX, PROPERTIES, PLAINTEXT
}
